import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono} from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-jetbrains', // Custom CSS variable name
});

export const metadata: Metadata = {
  title: "Kelvin Fang",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${jetbrainsMono.variable} ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-surface">
        <Nav />
        {children}
      </body>
    </html>
  );
}
